In [5]:
import numpy as np
import tensorflow as tf
from tensorflow import keras
import pandas as pd
import matplotlib.pyplot as plt
%matplotlib inline

In [6]:
df = pd.read_csv("insurance_data.csv")
df.head()

age  affordibility  bought_insurance
0   22              1                 0
1   25              0                 0
2   47              1                 1
3   52              0                 0
4   46              1                 1

In [7]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test =train_test_split(df[['age', 'affordibility']], df.bought_insurance, test_size=0.2, random_state=25)

In [8]:
X_train

age  affordibility
0    22              1
13   29              0
6    55              0
17   58              1
24   50              1
19   18              1
25   54              1
16   25              0
20   21              1
3    52              0
7    60              0
1    25              0
5    56              1
27   46              1
8    62              1
18   19              0
12   27              0
23   45              1
22   40              1
15   55              1
26   23              1
4    46              1

In [9]:
len(X_train)

22

In [10]:
df.shape

(28, 3)

In [11]:
X_train_scaled= X_train.copy()
X_train_scaled['age']= X_train_scaled['age']/100

X_test_scaled = X_test.copy()
X_test_scaled['age'] = X_test_scaled['age']/100


In [12]:
X_train_scaled

age  affordibility
0   0.22              1
13  0.29              0
6   0.55              0
17  0.58              1
24  0.50              1
19  0.18              1
25  0.54              1
16  0.25              0
20  0.21              1
3   0.52              0
7   0.60              0
1   0.25              0
5   0.56              1
27  0.46              1
8   0.62              1
18  0.19              0
12  0.27              0
23  0.45              1
22  0.40              1
15  0.55              1
26  0.23              1
4   0.46              1

In [13]:
model = keras.Sequential([
    keras.layers.Dense(1, input_shape=(2,), activation = 'sigmoid', kernel_initializer = 'ones', bias_initializer = 'zeros')
])
model.compile(optimizer = 'adam',
             loss= 'binary_crossentropy',
             metrics= ['accuracy'])
model.fit(X_train_scaled, y_train, epochs = 100)

Epoch 1/100


C:\Users\Shorab\AppData\Roaming\Python\Python312\site-packages\keras\src\layers\core\dense.py:87: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)


1/1 ━━━━━━━━━━━━━━━━━━━━ 1s 755ms/step - accuracy: 0.5000 - loss: 0.7113
Epoch 2/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 27ms/step - accuracy: 0.5000 - loss: 0.7110
Epoch 3/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 25ms/step - accuracy: 0.5000 - loss: 0.7106
Epoch 4/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 26ms/step - accuracy: 0.5000 - loss: 0.7102
Epoch 5/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 26ms/step - accuracy: 0.5000 - loss: 0.7098
Epoch 6/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 27ms/step - accuracy: 0.5000 - loss: 0.7094
Epoch 7/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 26ms/step - accuracy: 0.5000 - loss: 0.7091
Epoch 8/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 26ms/step - accuracy: 0.5000 - loss: 0.7087
Epoch 9/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 31ms/step - accuracy: 0.5000 - loss: 0.7083
Epoch 10/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 24ms/step - accuracy: 0.5000 - loss: 0.7079
Epoch 11/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 29ms/step - accuracy: 0.5000 - loss: 0.7076
Epoch 12/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 29ms/step - accuracy: 0.5000 - loss: 0.7072


In [14]:
X_test_scaled

age  affordibility
2   0.47              1
10  0.18              1
21  0.26              0
11  0.28              1
14  0.49              1
9   0.61              1

In [15]:
model.predict(X_test_scaled)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 36ms/step


array([[0.77436495],
       [0.72521085],
       [0.5345473 ],
       [0.74288785],
       [0.77751434],
       [0.79574805]], dtype=float32)

In [16]:
y_test

2     1
10    0
21    0
11    0
14    1
9     1
Name: bought_insurance, dtype: int64

In [17]:
coef,intercept = model.get_weights()
coef,intercept

(array([[0.9057445 ],
        [0.90450823]], dtype=float32),
 array([-0.09708388], dtype=float32))

# Now Building Neural Network from scratch without Tensorflow


In [18]:
def sigmoid(x):
    import math
    return 1/(1+math.exp(-x))
sigmoid(18)


0.9999999847700205

In [19]:
def prediction_function(age, affordibility):
    weighted_sum = coef[0]*age+coef[1]*affordibility+intercept
    return sigmoid(weighted_sum)

In [20]:
prediction_function(0.47,1)

C:\Users\Shorab\AppData\Local\Temp\ipykernel_19268\1966246136.py:3: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  return 1/(1+math.exp(-x))


0.7743649243286069

# Gradient Descent from scratch


In [21]:
def log_loss(y_true, y_predicted):
    epsilon = 1e-15
    y_predicted_new = [max(i, epsilon) for i in y_predicted]
    y_predicted_new = [min(i, 1-epsilon) for i in y_predicted_new]
    y_predicted_new= np.array(y_predicted_new)
    return -np.mean(y_true*np.log(y_predicted_new)+(1-y_true)*np.log(1-y_predicted_new))
    

In [22]:
def sigmoid_numpy(X):
    return 1/(1+np.exp(-X))
sigmoid_numpy(np.array([12,0,1]))

array([0.99999386, 0.5       , 0.73105858])

In [23]:
def gradient_descent(age, affordibility, y_true, epochs, loss_thresold):
    # w1, w2, bias
    w1=w2= 1
    bias = 0
    rate = 0.5
    n= len(age)
    for i in range(epochs):
        weighted_sum = w1*age+ w2*affordibility+bias
        y_predicted= sigmoid_numpy(weighted_sum)
        loss = log_loss(y_true, y_predicted)
        w1d = (1/n)*np.dot(np.transpose(age), (y_predicted - y_true))
        w2d = (1/n)*np.dot(np.transpose(affordibility), (y_predicted - y_true))
        bias_d = np.mean(y_predicted -y_true )
        w1 = w1 -rate* w1d
        w2 = w2 -rate* w2d
        bias = bias - rate*bias_d

        print(f'Epoch:{i}, w1:{w1}, w2:{w2}, bias:{bias}, loss:{loss}')
        if loss <=loss_thresold:
            break
    return w1, w2, bias


In [24]:
gradient_descent(X_train_scaled['age'], X_train_scaled['affordibility'], y_train, 1000, 0.6008)

Epoch:0, w1:0.974907633470177, w2:0.948348125394529, bias:-0.11341867736368583, loss:0.7113403233723417
Epoch:1, w1:0.9556229728273669, w2:0.9058873696677865, bias:-0.2122349122718517, loss:0.681264778737757
Epoch:2, w1:0.9416488476693794, w2:0.8719790823960313, bias:-0.2977578997796538, loss:0.6591474252715025
Epoch:3, w1:0.9323916996249162, w2:0.8457541517722915, bias:-0.3715094724003511, loss:0.6431523291301917
Epoch:4, w1:0.9272267472726993, w2:0.8262362885332687, bias:-0.43506643026891584, loss:0.6316873063379158
Epoch:5, w1:0.9255469396815343, w2:0.8124402814952774, bias:-0.48994490058938817, loss:0.623471707997592
Epoch:6, w1:0.9267936114129968, w2:0.8034375029757677, bias:-0.5375299543522853, loss:0.6175321183044205
Epoch:7, w1:0.93047170420295, w2:0.7983920007454487, bias:-0.5790424270894963, loss:0.6131591858705934
Epoch:8, w1:0.9361540784567942, w2:0.7965748796787705, bias:-0.6155315088627655, loss:0.6098518179750948
Epoch:9, w1:0.9434791243557357, w2:0.7973647616854131, bia

(0.9839042828641819, 0.8174345999952901, -0.7488554155033402)

In [25]:
coef, intercept

(array([[0.9057445 ],
        [0.90450823]], dtype=float32),
 array([-0.09708388], dtype=float32))

#w1 =1.1257616 w2 = 0.7468925 bias = -0.68011606

# Gradient Diescent Custom NN

In [38]:
class myNN:
    def __init__(self):
        # it is a constructor
        self.w1 =1
        self.w2 = 1
        self.bias = 0
        
    def fit(self, X,y, epochs, loss_thresold):
        self.w1, self.w2, self.bias = self.gradient_descent(X['age'], X['affordibility'], y, epochs, loss_thresold)

    def predict(self, X_test):
        weighted_sum = self.w1*X_test['age'] + self.w2* X_test['affordibility'] + self.bias
        return sigmoid_numpy(weighted_sum)

    
    def gradient_descent(self, age, affordibility, y_true, epochs, loss_thresold):
            # w1, w2, bias
        w1=w2= 1
        bias = 0
        rate = 0.5
        n= len(age)
        for i in range(epochs):
            weighted_sum = w1*age+ w2*affordibility+bias
            y_predicted= sigmoid_numpy(weighted_sum)
            loss = log_loss(y_true, y_predicted)
            w1d = (1/n)*np.dot(np.transpose(age), (y_predicted - y_true))
            w2d = (1/n)*np.dot(np.transpose(affordibility), (y_predicted - y_true))
            bias_d = np.mean(y_predicted -y_true )
            w1 = w1 -rate* w1d
            w2 = w2 -rate* w2d
            bias = bias - rate*bias_d

            if i%50==0:
                print(f'Epoch:{i}, w1:{w1}, w2:{w2}, bias:{bias}, loss:{loss}')
            if loss <=loss_thresold:
                print(f'Epoch:{i}, w1:{w1}, w2:{w2}, bias:{bias}, loss:{loss}')
                break
        return w1, w2, bias
        

In [39]:
customModel = myNN()
customModel.fit(X_train_scaled, y_train, epochs= 500, loss_thresold = 0.4631)

Epoch:0, w1:0.974907633470177, w2:0.948348125394529, bias:-0.11341867736368583, loss:0.7113403233723417
Epoch:50, w1:1.503319554173139, w2:1.108384790367645, bias:-1.2319047301235464, loss:0.5675865113475955
Epoch:100, w1:2.2007131317600317, w2:1.2941584023238906, bias:-1.6607009122062801, loss:0.5390680417774752
Epoch:150, w1:2.8495727769689077, w2:1.369689549157275, bias:-1.986105845859897, loss:0.5176462164249294
Epoch:200, w1:3.443016970881803, w2:1.4042218624465033, bias:-2.2571369883752723, loss:0.5005011269691375
Epoch:250, w1:3.982450494649576, w2:1.4239127329321233, bias:-2.494377365971801, loss:0.48654089537617085
Epoch:300, w1:4.472179522095915, w2:1.438787986553552, bias:-2.707387811922373, loss:0.4750814640632793
Epoch:350, w1:4.917245868007634, w2:1.4525660781176122, bias:-2.901176333556766, loss:0.46561475306999006
Epoch:366, w1:5.051047623653049, w2:1.4569794548473887, bias:-2.9596534546250037, loss:0.46293944095888917


In [40]:
coef, intercept

(array([[0.9057445 ],
        [0.90450823]], dtype=float32),
 array([-0.09708388], dtype=float32))

In [41]:
customModel.predict(X_test_scaled)

2     0.705020
10    0.355836
21    0.161599
11    0.477919
14    0.725586
9     0.828987
dtype: float64

In [42]:
model.predict(X_test_scaled)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 36ms/step


array([[0.77436495],
       [0.72521085],
       [0.5345473 ],
       [0.74288785],
       [0.77751434],
       [0.79574805]], dtype=float32)